module.exports = {
    functions: {
        arrayToObjectWithIdAsKeyReducer: require('./functions/arrayToObjectWithIdAsKeyReducer'),
        capitalizeFirstLetter: require('./functions/capitalizeFirstLetter'),
        getPrefix: require('./functions/getPrefix'),
        imageUrl: require('./functions/imageUrl'),
        parseGrade: require('./functions/parseGrade'),
        parseInheritance: require('./functions/parseInheritance'),
        parseQuery: require('./functions/parseQuery'),
        random: require('./functions/random'),
        range: require('./functions/range'),
        splitText: require('./functions/splitText'),
        statsToString: require('./functions/statsToString'),
        sumStats: require('./functions/sumStats'),
        toClearNumber: require('./functions/toClearNumber'),
        translateStat: require('./functions/translateStat'),
        makePullImage: require('./functions/makePullImage'),
        localImagePath: require('./functions/localImagePath'),
        createImage: require('./functions/createImage'),
        makeInRange: require('./functions/makeInRange'),
    },
    fileDb: require('./cq-data'),
    categories: require('./categories'),
    cmdResult: require('./results'),
    PaginationEmbed: require('../embeds/PaginationEmbed'),
};
