ALTER TABLE `cqdata`.`aliases`
CHARACTER SET = utf8,
CHANGE COLUMN `alias` `alias` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
CHANGE COLUMN `for` `for` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL;

ALTER TABLE `cqdata`.`translations`
CHARACTER SET = utf8,
CHANGE COLUMN `key` `key` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
CHANGE COLUMN `text` `text` TEXT CHARACTER SET 'utf8' NOT NULL,
CHANGE COLUMN `version` `version` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL DEFAULT '0.0.0';

ALTER TABLE `cqdata`.`stats` CHARACTER SET = utf8,
CHANGE COLUMN `arguments` `arguments` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
CHANGE COLUMN `user_id` `user_id` VARCHAR(25) CHARACTER SET 'utf8' NOT NULL,
CHANGE COLUMN `channel_id` `channel_id` VARCHAR(25) CHARACTER SET 'utf8' NOT NULL,
CHANGE COLUMN `sent_to` `sent_to` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL,
CHANGE COLUMN `content` `content` TEXT CHARACTER SET 'utf8' NOT NULL,
CHANGE COLUMN `command` `command` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
CHANGE COLUMN `target` `target` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL;

