module.exports = {
	arrayToObjectWithIdAsKeyReducer: require('./arrayToObjectWithIdAsKeyReducer'),
	capitalizeFirstLetter: require('./capitalizeFirstLetter'),
	getPrefix: require('./getPrefix'),
	imageUrl: require('./imageUrl'),
	parseGrade: require('./parseGrade'),
	parseInheritance: require('./parseInheritance'),
	parseQuery: require('./parseQuery'),
	random: require('./random'),
	range: require('./range'),
	splitText: require('./splitText'),
	statsToString: require('./statsToString'),
	sumStats: require('./sumStats'),
	toClearNumber: require('./toClearNumber'),
	translateStat: require('./translateStat'),
	makePullImage: require('./makePullImage'),
	localImagePath: require('./localImagePath'),
	createImage: require('./createImage'),
	makeInRange: require('./makeInRange'),
	pickGrade: require('./pickGrade'),
	extractMentions: require('./extractMentions'),
	getPermittedCommands: require('./getPermittedCommands'),
	formatPullChunks: require('./formatPullChunks'),
	chancesRoll: require('./chancesRoll'),
};
